global using InventoryManagementSystemApi.Modles.Setup.InventoryItemListRespnseModel;
global using InventoryManagementSystemApi.Modles.Setup.InventoryItem;
global using InventoryManagementSystemApi.Modles.Setup.PageSetting;
global using System;
global using System.Collections.Generic;
global using System.Text;
global using System.Threading.Tasks;
global using System.Linq;
global using InventoryManagementSystemApi.Modles;